chore_hero/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  resources :users
  resources :children
  resources :badges
  resources :chores

  get '/complete_chore/:id', to: 'chores#complete_chore', as: 'complete_chore'
  #post '/complete_chore/:id', to: 'chores#complete_chore', as: 'complete_chore'

  get '/faq', to: 'static_pages#faq', as: 'faq'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/charts', to: 'static_pages#charts', as: 'charts'
  get '/chores_assigned', to: 'chores#assigned'
  get '/badges_assigned', to: 'badges#assigned'

end

chore_hero/app/views/layouts/_footer.html.haml
.section.indigo.darken-4
  .row
    %footer.page-footer.headline
      .container-fluid
        .col.s12.center-align
          %h5.white-text Chore Hero
          %a= link_to "About", about_path, class: 'white-text'
          |
          %a= link_to "FAQ", faq_path, class: 'white-text'
          |
          %a= link_to "Home", root_path, class: 'white-text'

chore_hero/app/views/layouts/_navbar.html.haml
%nav#nav
  .nav-wrapper
    %ul.left.hide-on-med-and-down.headline
      %li= link_to "About", about_path
      %li= link_to "FAQ", faq_path
      %li= link_to "Home", root_path
      %a.headline#logo.brand-logo.center Chore Hero
    %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
      %i.material-icons menu
    %ul.right.hide-on-med-and-down.headline
      %li
        - if user_signed_in?
          %li= image_tag(current_user.avatar.url(:thumb), width: '70', height: '63')
          - if current_user.type == 'Parent'
            %li= link_to "Your Profile", user_path(current_user)
            %li= link_to "Charts", charts_path, class: "white-text"
            %li= link_to "Chores", chores_path
            %li= link_to "Rewards", badges_path
            %li= link_to 'Log Out', destroy_user_session_path, method: :delete

          - else
            %li= link_to "Your Profile", child_path(current_user)
            %li= link_to "Chores", chores_path
            %li= link_to "Rewards", badges_path
            %li= link_to 'Log Out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Parent / Child Log In', new_user_session_path
          %li= link_to 'Parent Sign Up', new_user_registration_path
    %ul#mobile-demo.side-nav.indigo.darken-4.left-align.headline
      %li= link_to 'Home', root_path, class: "white-text"
      %li= link_to 'FAQ', faq_path, class: "white-text"
      %li= link_to "About", about_path, class: "white-text"
      -if user_signed_in?
        - if current_user.parent?
          %li= link_to 'Your Profile', user_path(current_user), class: "white-text"
          %li= link_to "Charts", charts_path, class: "white-text"
          %li= link_to 'Chores', chores_path, class: "white-text"
          %li= link_to "Rewards", badges_path, class: "white-text"
          %li= link_to 'Log Out',destroy_user_session_path, method: :delete, class: "white-text"
        - else current_user.type == "Child"
          %li= link_to 'Your Profile', child_path(current_user), class: "white-text"
          %li= link_to 'Chores', chores_path, class: "white-text"
          %li= link_to 'Log Out',destroy_user_session_path, method: :delete, class: "white-text"
      - else
        %li= link_to 'Parent / Child Log In', new_user_session_path, class: "white-text"
        %li= link_to 'Parent Sign Up', new_user_registration_path, class: "white-text"

chore_hero/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChoreHero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

chore_hero/app/views/layouts/application.html.haml
%head
  %title ChoreHero
  %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %link{:href => "https://fonts.googleapis.com/css?family=Permanent+Marker", :rel => "stylesheet", :type => "text/css"}
  %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css", :rel => "stylesheet"}
  %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"}
  %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
  %link
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}
    %link{:href => "https://fonts.googleapis.com/css?family=Bangers", :rel => "stylesheet", :type => "text/css"}
%body
  =render 'layouts/navbar'
  .oh

  =yield
%footer.footer
  =render 'layouts/footer'