chore_hero/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  resources :users
  resources :children
  resources :badges
  resources :chores

  get '/complete_chore/:id', to: 'chores#complete_chore', as: 'complete_chore'
  #post '/complete_chore/:id', to: 'chores#complete_chore', as: 'complete_chore'

  get '/faq', to: 'static_pages#faq', as: 'faq'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/charts', to: 'static_pages#charts', as: 'charts'
  get '/chores_assigned', to: 'chores#assigned'
  get '/badges_assigned', to: 'badges#assigned'

end

chore_hero/app/controllers/children/sessions_controller2.rb
class Children::SessionsControllers< Devise::SessionsController
end

chore_hero/app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :children, only: [:show, :edit, :update, :destroy]

  def index
    @children = Child.all
  end

  def show
  end

  def edit
  end

  def update
    if @child.update(children_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def new
    @child = Child.new(type: 'Child')
  end

  def create
    @child = current_user.children.new(children_params)
    if @child.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @child.destroy
    redirect_to user_path(current_user)
  end

  private

     def children_params
       params.require(:child).permit(:name, :password, :email, :user_id, :avatar)
     end

     def children
       @child = Child.find(params[:id])
     end
end

chore_hero/app/helpers/children_helper.rb
module ChildrenHelper
end

chore_hero/app/views/children/_form.html.haml
.container.headline
  .row
    %br
    %br
    %br
    = form_for @child do |f|
      .input-field.col.s12
        = f.label :name, class: "indigo-text"
        = f.text_field :name
      .input-field.col.s12
        = f.label :email, class: "indigo-text"
        = f.text_field :email
      - if params[:action] == 'new'
        .input-field.col.s12
          = f.label :password, class: "indigo-text"
          = f.password_field :password, class: 'materialize-textarea'
          %br
      .input.col.s12
        = f.file_field :avatar
        %br
        %br
      = link_to 'Cancel', user_path(current_user), id: "round", class: 'btn red darken-4 white-text z-depth-4'
      = f.submit 'Submit', id: "round", class: 'btn red darken-4 white-text z-depth-4'
      %br
      %br
      %br

chore_hero/app/views/children/edit.html.haml
.container.headline
  %h1 Editing Child: #{@child.name}
  %hr

= render ('form')

chore_hero/app/views/children/new.html.haml
.container.headline
  %h1.center-align New Child
  %hr
  = render('form')

chore_hero/app/views/children/show.html.haml
.jumbotron-profile.center-align
  %br
  = image_tag current_user.avatar.url(:medium), width: '300', height: '300'
- if current_user.type == 'Child'
  .container.headline
    .row
      .col.s12.center
        .center-align
          %br
          %h3#bold.headline #{current_user.name}'s Homepage
          %h3.headline XP Total: #{current_user.points_total}
    .row
      .col.s12
        %h3#profile_text.headline.center-align My Chores
        .col.s12.center-align
          /%a= link_to "Go Get Chores in the Mission Log", chores_path, class: "btn red darken-4 white-text"
          %br
        %hr
        - if current_user.chores.any?
          %table
            %thead
              %tr
                %th.center-align.indigo-text Chore
                %th.center-align.indigo-text XP Value
                / %th.center-align Chore Due Date

            %tbody
              - current_user.chores.each do |chore|
                - if chore.complete == false
                  %tr
                    %td.center-align
                      = chore.title
                    %td.center-align
                      = chore.xp_value
          %h4#profile_text.center-align.headline Completed Chores
          %table
            %thead
              %tr
                %th.center-align.indigo-text Chore
                %th.center-align.indigo-text XP Value

            %tbody
              - current_user.chores.each do |chore|
                - if chore.complete == true
                  %tr
                    %td.center-align
                      = chore.title
                    %td.center-align
                      = chore.xp_value              


        - else
          %h3.center-align No Chores, Ask for some more
        %br
        %hr
        %br

        - if current_user.badges.any?
          %br
          %h4#profile_text.headline.center-align Here are your REWARDS! Good job!
          %br
          %table
            %thead
              %tr
                %th.center-align.indigo-text Rewards

            %tbody
              - current_user.badges.each do |badge|
                %tr
                  %td.center-align
                    = badge.title
                  / %td.center-align
                  /   = badge.description
        - else
          %h4.headline.center-align You don't have any rewards, keep doing your chores!
        %br
        %br


  / This is the Parent's view of the Child Showpage, when logged in as a parent
- if current_user.parent?
  .container.center-align
    %h3#bold.headline.center-align You are viewing  #{@child.name}'s Homepage
    %br
    %br
    %br
    %br
    .row.headline
      .col.s12
        = image_tag @child.avatar.url(:medium)
        %br
        %br
        = link_to 'Profile', user_path(current_user), id: "round", class: 'btn red darken-4 white-text z-depth-5'
        %br
        %br
        %a= link_to 'Edit Child', edit_child_path, id: "round", class: 'btn red darken-4 white-text z-depth-4'
        %a= link_to 'Add Chore', new_chore_path, id: "round", class: 'btn red darken-4 white-text z-depth-4'
        %a= link_to 'Add Reward', new_badge_path, id: "round", class: 'btn red darken-4 white-text z-depth-4'
        %br
        %br
        %br
        %hr
        - if @child.chores.any?
          %h4.headline Chores
          %table.col.s12
            %thead
              %tr
                %th.center-align Chore
                %th.center-align XP Value
                %th.center-align Action

            %tbody
              - @child.chores.each do |chore|
                - if chore.complete == false
                  %tr
                    %td.center-align
                      = chore.title
                    / %td.center-align
                    /   = chore.description
                    %td.center-align
                      = chore.xp_value
                    %td.center-align
                      %span
                        = link_to 'Edit Chore', edit_chore_path(chore)
                      %span
                        |
                        = link_to 'Delete Chore', chore_path(chore), method: 'delete', data: {confirm: '  Really  Delete?'}
                      %span
                        |
                        = link_to 'Mark Complete', complete_chore_path(chore)

          %h4.headline.add_margin Completed Chores
          %table.col.s12
            %thead
              %tr
                %th.center-align Chore
                %th.center-align XP Value
                %th.center-align Action              
            %tbody
              - @child.chores.each do |chore|
                - if chore.complete == true
                  %tr
                    %td.center-align
                      = chore.title
                    / %td.center-align
                    /   = chore.description
                    %td.center-align
                      = chore.xp_value
                    %td.center-align
                      %span
                        = link_to 'Edit Chore', edit_chore_path(chore)
                      %span
                        |
                        = link_to 'Delete Chore', chore_path(chore), method: 'delete', data: {confirm: '  Really  Delete?'}
                              
        - else
          %h3 No Chores assigned

      %br
        - if @child.badges.any?
          %h4.headline.add_margin Rewards
          %table
            %thead
              %tr
                %th.center-align Rewards
                %th.center-align Action

            %tbody
              - @child.badges.each do |badge|
                %tr
                  %td.center-align
                    = badge.title
                  %td.center-align
                    %span
                      = link_to 'Edit Reward', edit_badge_path(badge), method: 'get'
                    %span
                      |
                      = link_to 'Delete Reward', badge_path(badge), method: 'delete', data: {confirm: '  Really  Delete?'}

        - else
          %h4.headline #{@child.name} doesn't have any rewards.
    %br
    %br
    %br
    %br
    %br
    %br